"""add status to event

Revision ID: 4b7b4073a959
Revises: 835911d23acc
Create Date: 2024-05-25 09:07:54.881133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b7b4073a959'
down_revision: Union[str, None] = '835911d23acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('status', sa.Enum('green', 'red', 'orange', name='eventstatusenum', native_enum=False, length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'status')
    # ### end Alembic commands ###
