"""add datetime to event

Revision ID: d8beabcb2a3f
Revises: 2e2a4ec650a9
Create Date: 2024-05-18 20:06:14.875622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8beabcb2a3f'
down_revision: Union[str, None] = '2e2a4ec650a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('event_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'event_date')
    # ### end Alembic commands ###
